name: CI/CD for Firebase

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd functions
          npm install

      - name: Run Tests
        run: |
          cd functions
          npm test

      - name: Deploy to Firebase
        if: success()  # only run deploy if tests pass
        uses: sws2apps/firebase-deployment@main
        with:
          workloadIdentityProvider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          serviceAccount: ${{ secrets.SERVICE_ACCOUNT }}
          node-version: 18 # Optional, but recommended
          config: 'firebase.json' # Optional, path to your firebase.json
          function: true # Optional & boolean
          hosting: true # Optional & boolean
          project: studybuddy-1b01f # Required