name: CI/CD for Firebase

on:
  push:
    branches: [ "main" ]
permissions: read-all
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd functions
          npm install

      - name: Run Tests
        run: |
          cd functions
          npm test


      - name: Deploy to Firebase
        if: success()  # only run deploy if tests pass
        uses: sws2apps/firebase-deployment@main #consider using pin for dependabot auto update
        with:
          workloadIdentityProvider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          serviceAccount: ${{ secrets.SERVICE_ACCOUNT }}
          function: true #optional & boolean
          hosting: true #optional & boolean
          project: studybuddy-1b01f #required



